<?php

namespace AppBundle\Repository;

/**
 * StudentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class StudentRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * @param array $params
     * @return array
     */
    public function getAll($params = array()){
        $query = $this->createQueryBuilder('s')
            ->select('s');

        if(isset($params['search']) && !empty($params['search'])){
            $query->where("(s.name LIKE :search OR s.email LIKE :search OR s.phone LIKE :search)")
                ->setParameter('search', "%".$params['search']."%");
        }

        return $query->getQuery()->getResult();
    }
}
